"""
main.py — FastAPI skeleton for Repochat (Phase 1).

Routes:
  POST /index  — receive GitHub URL, return mock brief + session_id
  POST /chat   — receive session_id + question, return mock answer

All responses are hardcoded mocks in Phase 1.
Real orchestration is wired in Phase 4.
Every call/success/error is logged to logs/repochat.log.
"""

import os
import re
import time

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, field_validator

from logger import get_logger, log_endpoint
from session import create_session, require_session

# ── env & logger ───────────────────────────────────────────────────────────────
load_dotenv()
log = get_logger("repochat.main")

# Warn loudly on startup if keys are missing (Phase 1 runs without them,
# later phases will hard-fail without them).
_GITHUB_TOKEN  = os.getenv("GITHUB_TOKEN", "")
_GEMINI_KEY    = os.getenv("GEMINI_API_KEY", "")

if not _GITHUB_TOKEN:
    log.warning("GITHUB_TOKEN not set in .env — GitHub MCP calls will fail in Phase 2+")
if not _GEMINI_KEY:
    log.warning("GEMINI_API_KEY not set in .env — Gemini calls will fail in Phase 4+")

# ── app ────────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Repochat API",
    description="AI-powered GitHub repository intelligence — Phase 1 skeleton",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # tighten in production
    allow_methods=["*"],
    allow_headers=["*"],
)

log.info("Repochat API starting up")


# ── request / response models ──────────────────────────────────────────────────

_GITHUB_URL_RE = re.compile(
    r"^https?://github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+?)(/.*)?$"
)


class IndexRequest(BaseModel):
    url: str

    @field_validator("url")
    @classmethod
    def validate_github_url(cls, v: str) -> str:
        if not _GITHUB_URL_RE.match(v.strip()):
            raise ValueError("URL must be a valid GitHub repository URL (https://github.com/owner/repo)")
        return v.strip()


class ChatRequest(BaseModel):
    session_id: str
    question:   str


# ── helpers ────────────────────────────────────────────────────────────────────

def _parse_owner_repo(url: str) -> tuple[str, str]:
    m = _GITHUB_URL_RE.match(url)
    if not m:
        raise ValueError(f"Cannot parse owner/repo from {url!r}")
    return m.group("owner"), m.group("repo")


# ── routes ─────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    """Simple liveness probe."""
    log.info("Health check OK")
    return {"status": "ok", "version": app.version}


@app.post("/index")
@log_endpoint("POST /index")
async def index_repo(body: IndexRequest):
    """
    Receive a GitHub repo URL.
    Phase 1: creates session, returns hardcoded mock brief.
    Phase 4: will call orchestrator.run() to produce a real brief.
    """
    t0 = time.perf_counter()

    try:
        owner, repo = _parse_owner_repo(body.url)
    except ValueError as e:
        log.api_error("POST /index", error=str(e), url=body.url)
        raise HTTPException(status_code=422, detail=str(e))

    log.info(f"Indexing repo owner={owner!r} repo={repo!r}")

    session_id = create_session(owner=owner, repo=repo, url=body.url)
    log.info(f"Session created session_id={session_id}")

    # ── MOCK response (replaced in Phase 4) ───────────────────────────────
    mock_brief = {
        "architecture": (
            f"[MOCK] {owner}/{repo} appears to be a well-structured repository. "
            "Architecture analysis will be generated by Gemini in Phase 4."
        ),
        "core_modules": [
            {"file": "index.js",       "role": "Entry point",       "badge": "⚡ Core"},
            {"file": "src/router.js",  "role": "Request routing",   "badge": "🔀 Router"},
            {"file": "src/utils.js",   "role": "Shared utilities",  "badge": "🛠 Util"},
        ],
        "hidden_signals": [
            {
                "type":   "violation",
                "title":  "[MOCK] Architectural Outlier Detected",
                "detail": "One file appears to bypass the dominant middleware pattern. "
                          "Real detection runs in Phase 3.",
                "source": "signal_agent (mock)",
            }
        ],
        "unused_data": [
            {"field": "legacy_flag", "note": "Defined but never referenced", "tag": "🗑 Stale"},
        ],
    }

    duration_ms = (time.perf_counter() - t0) * 1000
    log.api_success("POST /index", duration_ms=duration_ms, session_id=session_id, owner=owner, repo=repo)

    return {
        "session_id": session_id,
        "brief":      mock_brief,
    }


@app.post("/chat")
@log_endpoint("POST /chat")
async def chat(body: ChatRequest):
    """
    Receive a session_id and a question.
    Phase 1: validates session exists, returns hardcoded mock answer.
    Phase 4: will classify question and call Gemini with real context.
    """
    t0 = time.perf_counter()

    try:
        session = require_session(body.session_id)
    except ValueError as e:
        log.api_error("POST /chat", error=str(e), session_id=body.session_id)
        raise HTTPException(status_code=404, detail=str(e))

    owner = session["repo_meta"]["owner"]
    repo  = session["repo_meta"]["repo"]

    log.info(
        f"Chat question session_id={body.session_id!r} "
        f"repo={owner}/{repo} question={body.question!r}"
    )

    # ── MOCK response (replaced in Phase 4) ───────────────────────────────
    mock_answer = (
        f"[MOCK] You asked: '{body.question}'\n\n"
        f"Real answers about {owner}/{repo} will be generated by Gemini in Phase 4, "
        "after the question classifier and orchestrator are wired up."
    )

    duration_ms = (time.perf_counter() - t0) * 1000
    log.api_success(
        "POST /chat",
        duration_ms=duration_ms,
        session_id=body.session_id,
        question_len=len(body.question),
    )

    return {
        "answer":  mock_answer,
        "sources": ["[MOCK] src/index.js", "[MOCK] src/router.js"],
    }


# ── startup / shutdown events ──────────────────────────────────────────────────

@app.on_event("startup")
async def on_startup():
    log.info("=" * 60)
    log.info("Repochat API is ready")
    log.info(f"  GITHUB_TOKEN set : {'YES' if _GITHUB_TOKEN else 'NO ⚠'}")
    log.info(f"  GEMINI_KEY   set : {'YES' if _GEMINI_KEY   else 'NO ⚠'}")
    log.info("=" * 60)


@app.on_event("shutdown")
async def on_shutdown():
    log.info("Repochat API shutting down")
